export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAIL = 'LOGIN_FAIL'; 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; 
export const REGISTER_FAIL = 'REGISTER_FAIL'; 

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; 

export const PRODUCT_LIST_SUCCESS =  'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL =  'PRODUCT_LIST_FAIL';
export const PRODUCT_DETAIL_SUCCESS =  'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL =  'PRODUCT_DETAIL_FAIL';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';

export const FETCH_CART = 'FETCH_CART';


export const CREATE_ORDER = 'CREATE_ORDER';
export const FETCH_ORDER = 'FETCH_ORDER';

